<?php

namespace DTRE\OeilBundle\Repository;

/**
 * DailyDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDataDay(\Datetime $date)
    {
        $dateDay= new \DateTime($date->format("Y-m-d"));
        $qb = $this->createQueryBuilder("d");

        $qb->select('d')
            ->where('d.date = :date')
            ->setParameter('date', $dateDay);

        return $qb->getQuery()
            ->getResult();
    }
}
