<?php

namespace DTRE\OeilBundle\Repository;

/**
 * DailyDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyDataRepository extends \Doctrine\ORM\EntityRepository
{
}
