<?php

namespace DTRE\OeilBundle\Repository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDay($id, \Datetime $date)
    {
        $from = new \DateTime($date->format("Y-m-d")." 00:00:00");
        $to   = new \DateTime($date->format("Y-m-d")." 23:59:59");

        $qb = $this->createQueryBuilder("d");
        $qb
            ->join('d.sensor', 's')
            ->where('s.id = :id')
            ->andWhere('d.date BETWEEN :from AND :to')
            ->setParameter('from', $from )
            ->setParameter('to', $to)
            ->setParameter('id', $id)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
